export const errorEndpoint = () => {
  throw new Error("This is a test error triggered by the error endpoint.");
};
